config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  get 'spotify/search'
  resources :tracks
  resources :playlists

  # Index/Home route
  root to: 'tracks#index'
end

app/models/application_record.rb
# frozen_string_literal: true

# ApplicationRecord class
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/playlist.rb
# frozen_string_literal: true

class Playlist < ApplicationRecord
  validates :name, presence: true
  validates :number_of_votes, presence: true
end

app/models/track.rb
# frozen_string_literal: true

class Track < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/playlists_controller.rb
# frozen_string_literal: true

# PlaylistController class with CRUD methods
class PlaylistsController < ApplicationController
  before_action :authenticate_user!

  def index
    @playlists = Playlist.all
  end

  def show
    @playlist = Playlist.find(params[:id])
  end

  def new
    @playlist = Playlist.new
  end

  def edit; end

  def create
    @playlist = Playlist.new(playlist_params)
    if @playlist.save
      redirect_to @playlist
    else
      render :new
    end
  end

  def playlist_params
    params.require(:playlist).permit(:name, :number_of_votes)
  end
end

app/controllers/spotify_controller.rb
# frozen_string_literal: true

class SpotifyController < ApplicationController
  def search
    title = params[:title]
    return @results = RSpotify::Track.search(title) if title
  end
end

app/controllers/tracks_controller.rb
# frozen_string_literal: true

# TracksController class with CRUD methods
class TracksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_track, only: %i[show edit update destroy]

  # GET /tracks
  # GET /tracks.json
  def index
    @tracks = Track.all
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show; end

  # GET /tracks/new
  def new
    @track = Track.new
  end

  # GET /tracks/1/edit
  def edit; end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = Track.new(track_params)

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: 'Track was successfully created.' }
        format.json { render :show, status: :created, location: @track }
      else
        format.html { render :new }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracks/1
  # PATCH/PUT /tracks/1.json
  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
        format.json { render :show, status: :ok, location: @track }
      else
        format.html { render :edit }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    @track.destroy
    respond_to do |format|
      format.html { redirect_to tracks_url, notice: 'Track was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_track
    @track = Track.find(params[:id])
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def track_params
    params.require(:track).permit(:title, :album, :artist)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# ApplicationHelper module
module ApplicationHelper
end

app/helpers/playlists_helper.rb
# frozen_string_literal: true

module PlaylistsHelper
end

app/helpers/spotify_helper.rb
# frozen_string_literal: true

module SpotifyHelper
end

app/helpers/tracks_helper.rb
# frozen_string_literal: true

# TracksHelper module
module TracksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rubymusic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/playlists/_form.html.erb
<%= form_with(model: playlist, local: true) do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :number_of_votes %>
    <%= form.text_field :number_of_votes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/playlists/edit.html.erb
<h1>Editing Playlist</h1>

<%= render 'form', playlist: @playlist %>

<%= link_to 'Show', @playlist %> |
<%= link_to 'Back', playlists_path %>

app/views/playlists/index.html.erb
<h1>Listado de listas de reproducción</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number of votes</th>
    </tr>
  </thead>
  <tbody>
    <% @playlists.each do |playlist| %>
      <tr>
        <td><%= playlist.name %></td>
        <td><%= playlist.number_of_votes %></td>
        <td><%= link_to 'Show', playlist %></td>
        <td><%= link_to 'Edit', edit_playlist_path(playlist) %></td>
        <td><%= link_to 'Destroy', playlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Track', new_playlist_path %>

app/views/playlists/new.html.erb
<%= form_for(@playlist) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :number_of_votes %>
  <%= f.text_field :number_of_votes %>
  <%= f.submit %>
<% end %>

app/views/playlists/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @playlist.name %>
  <strong>Votes:</strong>
  <%= @playlist.number_of_votes %>
</p>

<%= link_to 'Edit', edit_playlist_path(@playlist) %> |
<%= link_to 'Back', playlists_path %>

app/views/spotify/search.html.erb
<h1>Search Results</h1>
<ul>
  <% @results.each do |result| %>
    <li>
      <%= result.name%> - <%= result.album.name%>
    </li>
  <%end%>
</ul>

app/views/tracks/_form.html.erb
<%= form_with(model: track, local: true) do |form| %>
  <% if track.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
      <% track.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :album %>
    <%= form.text_field :album %>
  </div>

  <div class="field">
    <%= form.label :artist %>
    <%= form.text_field :artist %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tracks/edit.html.erb
<h1>Editing Track</h1>

<%= render 'form', track: @track %>

<%= link_to 'Show', @track %> |
<%= link_to 'Back', tracks_path %>

app/views/tracks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tracks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Album</th>
      <th>Artist</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tracks.each do |track| %>
      <tr>
        <td><%= track.title %></td>
        <td><%= track.album %></td>
        <td><%= track.artist %></td>
        <td><%= link_to 'Show', track %></td>
        <td><%= link_to 'Edit', edit_track_path(track) %></td>
        <td><%= link_to 'Destroy', track, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Track', new_track_path %>

<%= form_tag(spotify_search_path, method: :get) do %>
  <%= text_field_tag :title %>
  <%= submit_tag 'Search'%>
<%end%>

app/views/tracks/new.html.erb
<h1>New Track</h1>

<%= render 'form', track: @track %>

<%= link_to 'Back', tracks_path %>

app/views/tracks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @track.title %>
</p>

<p>
  <strong>Album:</strong>
  <%= @track.album %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @track.artist %>
</p>

<%= link_to 'Edit', edit_track_path(@track) %> |
<%= link_to 'Back', tracks_path %>